### PR TITLE
Add support for BBB v2.3 to export.js

### PR DESCRIPTION
**Pull request by amirhoseinsalimi**
Hi, hope you're doing well.

It seems the playback URL has changed in BBB v2.3. It looks like this:
`https://example.com/playback/presentation/2.3/5f3a37f42fb4e21f91153967bb441b9d6b5478ac-1611595759654`

Which is different from what we had in v2.2. To compare:
`https://example.com/playback/presentation/2.0/playback.html?meetingId=6de6c4496eb598eeb0d55c7c7e4b2a272521e447-1598884103247`
is a v2.2 playback URL.

So I extended/added the RegExp for v2.3. I tested it on one BBB instance <s>and  works</s>, maybe it's better to look at my implementation and if it's okay, then pull it to master. I'm going to test it w/ some other instances and make this PR a draft for now.
After I reviewed it more, I message you here.

Thank you.

P.S. (12:02 PM): The queue in which I put the new recording job has been failed. The problem is w/ CSS selectors, I think.

### CODE REVIEW

**Comment by amirhoseinsalimi** [comment]
Also, I should mention that this PR solves the new problem, for `export.js` file, not the live-recorder scripts. Regarding #79.

**Comment by amirhoseinsalimi** [comment]
Me again,
After a few weeks (which is so long), my manager gave me this task again, so I could spend some time figuring out what to add. Hopefully, I could find a PR [here](https://github.com/hooktstudios/bbb-recorder/commit/62c989d304a04fdf7aed565e729ac12f6d14848e) which was something like we had in [#79](https://github.com/jibon57/bbb-recorder/issues/79). However, these two code snippets only support v2.3, keeping the incompatibility b/w different versions, so the problem still there. Thus, I changed the code a bit and added a flag/variable called `bbbVersionIs23` to the code. This variable's value may change to `true` or `false` based on the given URL and later is used to interact with the page accordingly. This way we can record both v2.2 and v2.3.

**Comment by jibon57** [comment]
@amirhoseinsalimi I think it will be better if we verify it using selector. Because if you upgrade BBB 2.2 to 2.3 then old recordings will have previous link but it will redirect to new URL. I think this can be better approach. I'll update your PR.

**Comment by amirhoseinsalimi** [comment]
It makes sense. I wasn't aware of the redirection. I just tested it on a fresh BBB v2.3 server. Thanks in advance BTW.

**Comment by stevelacerda** [comment]
I'm getting NaN for recDuration in bbb 2.3

**Comment by clement850** [comment]
Hello, any news about this feature? I would like to download old recordings (from 2.2) on a 2.3 BBB server

Thanks in advance

**Comment by bkmgit** [comment]
Seems to work for 2.3 recordings. 
Maybe variables can be used for acorn and vjs for cleaner code.

**Comment by amirhoseinsalimi** [comment]
Here you are, @bkmgit.

**Comment by jibon57** [comment]
Thank you @amirhoseinsalimi

**Pull request merged**
